---
# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: ansible.posix
    version: ">=1.5.0"

  - name: community.general
    version: ">=6.0.0,<9.0.0"  # Compatible with Ansible 2.15
